config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"

  root to: "algorithms#index"

  get "/algorithms/returns", to: "algorithms#returns"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/algorithms_controller.rb
class AlgorithmsController < ApplicationController

    # def index
    #     returns(@value)
    #     render :returns
    # end

    def lists
        @name = "Robinson"

        @possui_son = @name.include? "son"
        @nome_letra_inicial = @name[0]

        @output=[@possui_son, @nome_letra_inicial]
    end

    def returns

        #      = params[:<valor inserido no formulario>]
        @value = params[:value]        

        @palindromo = eh_palindromo(@value)
        @maior_idade = maior_de_idade(@value)
    end

    def eh_palindromo(value)

        if value.nil? || value.strip.empty?
            return "Favor inserir algum valor!"
          end

        value = value.to_s
        @tamanho_valor = value.length

        if eh_par(value)
            @primeira_parte = value[0, @tamanho_valor/2]
            @segunda_parte = value[@tamanho_valor/2, @tamanho_valor]
        else
            @primeira_parte = value[0, (@tamanho_valor/2)]
            @segunda_parte = value[@tamanho_valor/2+1, @tamanho_valor]
        end

        if (@primeira_parte==@segunda_parte.reverse)
            return true
        else
            return false
        end
    end

    def maior_de_idade(value)

        if value.nil? || value.strip.empty?
            return "Favor inserir algum valor!"
        end

        value = value.to_i
        if (value<18)
            return "Usuário ainda é menor de idade!"
        else
            return "Usuário é maior de idade"
        end
    end
    

    private

    def eh_par(value)
        value = value.to_s
        return (value.length%2)==0
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/algorithms/index.html.erb
<h2>app/views/layout/index</h2>

app/views/algorithms/returns.html.erb
<%= form_with(url: algorithms_returns_path, method: "get") do |form| %>
    <div class="field">
      <%= form.label :value , "Digite o valor:" %>
      <%= form.text_field :value %>
    </div>
    <div class="actions">
      <%= form.submit "Calculate" %>
    </div>
  <%= @palindromo %>
  <% end %>

<%= form_with(url: algorithms_returns_path, method: "get") do |form| %>
    <div class="field">
      <%= form.label :value %>
      <%= form.text_field :value %>
    </div>
    <div class="actions">
      <%= form.submit "Calculate" %>
    </div>
  <%= @maior_idade %>
  <% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Algorithms</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <ul>
      <li>
        <a href="/algorithms/returns">API Returns: </a>
      </li>
    </ul>
    <%= yield %>
  </body>
</html>